"""
Silver Tier Orchestrator - Triggers Claude Code for reasoning and Plan.md creation.

Silver Tier Requirements implemented:
- Claude reasoning loop that creates Plan.md files
- Human-in-the-loop approval workflow
- Integration with MCP servers (Email, LinkedIn)
- Watcher integration (Gmail, WhatsApp, Filesystem)
"""

import os
import subprocess
import time
import shutil
from pathlib import Path
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from datetime import datetime

# Vault Path Configuration
PROJECT_ROOT = Path(__file__).parent.parent.parent
VAULT_PATH = PROJECT_ROOT / 'AI_Employee_Vault'

# Optional: Override with environment variable
if os.getenv('VAULT_PATH_OVERRIDE'):
    VAULT_PATH = Path(os.getenv('VAULT_PATH_OVERRIDE'))

# Directory definitions (inside the Obsidian Vault)
NEEDS_ACTION_DIR = VAULT_PATH / "Needs_Action"
PLANS_DIR = VAULT_PATH / "Plans"
PENDING_APPROVAL_DIR = VAULT_PATH / "Pending_Approval"
APPROVED_DIR = VAULT_PATH / "Approved"
DONE_DIR = VAULT_PATH / "Done"
LOGS_DIR = VAULT_PATH / "Logs"
REJECTED_DIR = VAULT_PATH / "Rejected"

# Skills directory (in project root, not vault)
SKILLS_DIR = PROJECT_ROOT / "skills"

# Ensure directories exist
for d in [NEEDS_ACTION_DIR, PLANS_DIR, PENDING_APPROVAL_DIR, APPROVED_DIR, DONE_DIR, LOGS_DIR, REJECTED_DIR]:
    d.mkdir(parents=True, exist_ok=True)


def log_event(event_type: str, data: dict, actor: str = "orchestrator"):
    """Log an event to the daily log file."""
    log_file = LOGS_DIR / f"{datetime.now().strftime('%Y-%m-%d')}.json"
    entry = {
        "timestamp": datetime.now().isoformat(),
        "event_type": event_type,
        "actor": actor,
        "data": data,
        "result": "success"
    }
    with open(log_file, "a") as f:
        import json
        f.write(json.dumps(entry) + "\n")
    return str(log_file)


def update_dashboard(status: str, last_action: str):
    """Update the Dashboard.md with current status."""
    dashboard_path = VAULT_PATH / "Dashboard.md"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Get pending approvals count
    pending_count = len(list(PENDING_APPROVAL_DIR.glob("*.md"))) if PENDING_APPROVAL_DIR.exists() else 0
    
    content = f"""# AI Employee Dashboard

**Last Updated**: {timestamp}

## System Status
{status}

## Last Action Taken
{last_action}

## Pending Approvals
{pending_count} item(s) awaiting approval

## Quick Links
- [Needs_Action](./Needs_Action/) - Tasks requiring attention
- [Pending_Approval](./Pending_Approval/) - Awaiting approval
- [Plans](./Plans/) - Generated action plans
- [Done](./Done/) - Completed tasks
- [Logs](./Logs/) - System logs

---
*Generated by AI Employee v0.2 - Silver Tier*
"""
    dashboard_path.write_text(content)
    return str(dashboard_path)


def trigger_claude_for_plan(task_file: Path) -> Path:
    """
    Trigger Claude Code to create a Plan.md for a task.
    
    Silver Tier: Claude reasoning loop that creates Plan.md files
    
    Args:
        task_file: Path to task file in Needs_Action/
        
    Returns:
        Path to created Plan.md file
    """
    log_event("claude.plan_request", {"task_file": str(task_file)})
    
    # Read task content
    task_content = task_file.read_text()
    
    # Build the prompt for Claude Code
    # This follows the Hackathon-0 spec for Claude reasoning
    prompt = f"""
You are an AI Employee (Silver Tier). A new task has been detected.

## Task File
{task_file.name}

## Task Content
{task_content}

## Your Skills
Read the skill files in /skills/ for your capabilities:
- 01_process_needs_action.md - Process items in Needs_Action
- 02_update_dashboard.md - Update the dashboard
- 03_request_approval.md - Request human approval when needed
- 04_execute_approved.md - Execute approved actions
- 05_log_events.md - Log all events
- 06_create_plan.md - Create detailed action plans

## Company Handbook
Always follow the rules in /Company_Handbook.md

## Your Task
1. Analyze the task above
2. Create a detailed Plan.md in /Plans/ with:
   - Clear objective
   - Step-by-step actions
   - Approval requirements (what needs human approval)
   - Success criteria
3. Log your actions
4. Update the Dashboard

## Plan Format
```markdown
---
type: plan
created: YYYY-MM-DDTHH:MM:SS
status: pending_approval
source: {{task_file}}
---

# Plan: {{Brief Description}}

## Objective
{{What needs to be accomplished}}

## Steps
- [ ] Step 1: ...
- [ ] Step 2: ...

## Approval Required
{{Yes/No - Explain}}
```

Remember:
- Never execute external actions without approval
- Always log your actions
- Be transparent about decisions
"""
    
    # Try to call Claude Code CLI
    dry_run = os.getenv("DRY_RUN", "true").lower() == "true"
    
    if dry_run:
        # In dry-run mode, simulate Claude's response by creating a plan
        plan_path = simulate_claude_plan(task_file, task_content)
        log_event("claude.plan_simulated", {"plan_file": str(plan_path)})
        return plan_path
    
    # Actually call Claude Code
    try:
        cmd = ["claude", "--prompt", prompt]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        
        if result.returncode == 0:
            log_event("claude.plan_completed", {"exit_code": result.returncode})
            # Claude should have created the plan file
            # Find the most recent plan file
            plan_files = sorted(PLANS_DIR.glob("plan_*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
            if plan_files:
                return plan_files[0]
        else:
            log_event("claude.plan_error", {"error": result.stderr})
            
    except FileNotFoundError:
        log_event("claude.not_found", {"message": "Claude CLI not installed"})
    except subprocess.TimeoutExpired:
        log_event("claude.timeout", {"task_file": str(task_file)})
    except Exception as e:
        log_event("claude.error", {"error": str(e)})
    
    # Fallback to simulation
    return simulate_claude_plan(task_file, task_content)


def simulate_claude_plan(task_file: Path, task_content: str) -> Path:
    """
    Simulate Claude Code creating a plan (for development/testing).
    
    In production with Claude Code installed, Claude would do this itself.
    """
    task_name = task_file.stem
    
    # Analyze task type
    task_lower = task_content.lower()
    if 'email' in task_lower:
        action_type = 'email_send'
        requires_approval = 'Yes - External communication requires approval'
    elif 'post' in task_lower or 'linkedin' in task_lower:
        action_type = 'social_media_post'
        requires_approval = 'Yes - Social media posts require approval'
    elif 'payment' in task_lower or 'invoice' in task_lower:
        action_type = 'payment'
        requires_approval = 'Yes - Financial transactions require approval'
    else:
        action_type = 'general_task'
        requires_approval = 'Yes - Requires human review'
    
    plan_content = f"""---
type: plan
created: {datetime.now().isoformat()}
status: pending_approval
source: {task_file}
action_type: {action_type}
---

# Plan: Process {task_name}

## Objective
Process the task: {task_content.strip()[:200]}

## Analysis
- **Task Type**: {action_type.replace('_', ' ').title()}
- **Priority**: Normal
- **Estimated Steps**: 3-4

## Steps
- [ ] Step 1: Analyze the request in detail
- [ ] Step 2: Determine required action and resources
- [ ] Step 3: Request human approval (required for this task type)
- [ ] Step 4: Execute action after approval
- [ ] Step 5: Log completion and move to Done

## Approval Required
{requires_approval}

Per Company Handbook rules:
- External communications require approval
- Financial transactions require approval
- Social media posts require approval

## Next Action
Move this plan to /Pending_Approval/ for human review.

---
*Generated by AI Employee (Silver Tier - Claude Simulation)*
"""
    
    plan_file = PLANS_DIR / f"plan_{task_name}.md"
    plan_file.write_text(plan_content)
    
    log_event("plan.created", {"plan_file": str(plan_file)})
    update_dashboard("Plan created", f"Generated plan for {task_name}")
    
    return plan_file


def move_plan_to_approval(plan_file: Path):
    """Move a plan to Pending_Approval for human review."""
    if plan_file.exists():
        dest = PENDING_APPROVAL_DIR / plan_file.name
        shutil.move(str(plan_file), str(dest))
        log_event("plan.moved_to_approval", {"plan_file": str(dest)})
        update_dashboard("Awaiting Approval", f"Plan {plan_file.name} pending review")
        return dest
    return None


def execute_approved_plan(approved_file: Path) -> bool:
    """
    Execute an approved plan using MCP servers.
    
    Silver Tier: Human-in-the-loop approval workflow
    
    Args:
        approved_file: Path to approved plan file
        
    Returns:
        True if executed successfully
    """
    log_event("execution.started", {"approved_file": str(approved_file)})
    
    content = approved_file.read_text()
    
    # Parse the approval file to determine action type
    if 'type: email_send' in content:
        # Execute email send via Email MCP
        from src.mcp.email_mcp import EmailMCP
        mcp = EmailMCP(str(VAULT_PATH))
        success = mcp.execute_approved_send(approved_file)
    elif 'type: linkedin_post' in content:
        # Execute LinkedIn post via LinkedIn Poster
        from src.mcp.linkedin_poster import LinkedInPoster
        poster = LinkedInPoster(str(VAULT_PATH))
        # Implementation would extract content and post
        success = True  # Placeholder
    else:
        # Generic task completion
        log_event("execution.generic", {"message": "Generic task execution"})
        success = True
    
    if success:
        # Move to Done
        done_file = DONE_DIR / approved_file.name
        shutil.move(str(approved_file), str(done_file))
        log_event("execution.completed", {"done_file": str(done_file)})
        update_dashboard("Task Complete", f"Executed {approved_file.name}")
    else:
        log_event("execution.failed", {"approved_file": str(approved_file)})
        update_dashboard("Execution Failed", f"Failed to execute {approved_file.name}")
    
    return success


# --- Event Handlers ---

class NeedsActionHandler(FileSystemEventHandler):
    """Watches for new tasks and triggers Claude Code to create plans."""
    
    def on_created(self, event):
        if event.is_directory:
            return
        if not event.src_path.endswith('.md'):
            return
        
        task_file = Path(event.src_path)
        log_event("orchestrator.new_task_detected", {"file": str(task_file)})
        update_dashboard("Processing", f"New task: {task_file.name}")
        
        # Trigger Claude to create a plan
        plan_file = trigger_claude_for_plan(task_file)
        
        if plan_file:
            # Move plan to approval
            move_plan_to_approval(plan_file)


class ApprovedHandler(FileSystemEventHandler):
    """Watches for approved plans and executes them."""
    
    def on_created(self, event):
        if event.is_directory:
            return
        if not event.src_path.endswith('.md'):
            return
        
        approved_file = Path(event.src_path)
        log_event("orchestrator.plan_approved", {"file": str(approved_file)})
        update_dashboard("Executing", f"Executing: {approved_file.name}")
        
        # Execute the approved plan
        execute_approved_plan(approved_file)


# --- Orchestrator ---

class Orchestrator:
    """
    Silver Tier Orchestrator with Claude reasoning loop and HITL workflow.
    """
    
    def __init__(self):
        self.observer = Observer()
        self.running = False
    
    def start(self):
        """Start watching directories."""
        log_event("orchestrator.started", {})
        update_dashboard("Idle", "Silver Tier Orchestrator started")
        
        # Schedule handlers
        self.observer.schedule(NeedsActionHandler(), str(NEEDS_ACTION_DIR), recursive=False)
        self.observer.schedule(ApprovedHandler(), str(APPROVED_DIR), recursive=False)
        
        self.observer.start()
        self.running = True
        
        print("=" * 60)
        print("AI Employee Orchestrator - Silver Tier")
        print("=" * 60)
        print(f"Vault Path: {VAULT_PATH}")
        print(f"Watching: Needs_Action/, Approved/")
        print(f"DRY_RUN: {os.getenv('DRY_RUN', 'true')}")
        print("=" * 60)
        print("Silver Tier Features:")
        print("  ✓ Claude reasoning loop (Plan.md creation)")
        print("  ✓ Human-in-the-loop approval workflow")
        print("  ✓ MCP server integration (Email, LinkedIn)")
        print("  ✓ Watcher integration (Gmail, WhatsApp, Filesystem)")
        print("=" * 60)
        print("Add files to /Needs_Action/ to trigger processing...")
        print("Press Ctrl+C to stop.")
        print("=" * 60)
    
    def stop(self):
        """Stop the orchestrator."""
        self.running = False
        self.observer.stop()
        self.observer.join()
        log_event("orchestrator.stopped", {})
        update_dashboard("Offline", "Orchestrator stopped")
        print("Orchestrator stopped.")
    
    def run(self):
        """Run the orchestrator main loop."""
        self.start()
        try:
            while self.running:
                time.sleep(1)
        except KeyboardInterrupt:
            self.stop()


if __name__ == "__main__":
    orchestrator = Orchestrator()
    orchestrator.run()
