"""
Dashboard utility - Update the AI Employee Dashboard.
"""

import os
from datetime import datetime
from pathlib import Path

# Vault Path Configuration
# The Obsidian Vault is located in AI_Employee_Vault/ within the project root
PROJECT_ROOT = Path(__file__).parent.parent.parent
VAULT_PATH = PROJECT_ROOT / 'AI_Employee_Vault'

# Optional: Override with environment variable
if os.getenv('VAULT_PATH_OVERRIDE'):
    VAULT_PATH = Path(os.getenv('VAULT_PATH_OVERRIDE'))

DASHBOARD_FILE = VAULT_PATH / "Dashboard.md"


def update_dashboard(last_action: str, status: str):
    """
    Updates the dashboard with the latest action and status.
    
    Args:
        last_action: Description of the last action taken
        status: Current system status (Idle, Processing, etc.)
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Get pending approvals count
    pending_approval_dir = VAULT_PATH / "Pending_Approval"
    pending_count = len(list(pending_approval_dir.glob("*.md"))) if pending_approval_dir.exists() else 0
    
    content = f"""# AI Employee Dashboard

**Last Updated**: {timestamp}

## System Status
{status}

## Last Action Taken
{last_action}

## Pending Approvals
{pending_count} item(s) awaiting approval

## Quick Links
- [Needs_Action](./Needs_Action/) - Tasks requiring attention
- [Pending_Approval](./Pending_Approval/) - Awaiting approval
- [Plans](./Plans/) - Generated action plans
- [Done](./Done/) - Completed tasks
- [Logs](./Logs/) - System logs

---
*Generated by AI Employee v0.1 - Bronze Tier*
"""
    
    with open(DASHBOARD_FILE, "w") as f:
        f.write(content)
    
    return str(DASHBOARD_FILE)


if __name__ == "__main__":
    update_dashboard("Test action", "Idle")
    print(f"Dashboard updated: {DASHBOARD_FILE}")
